/**
 * Writes infra/terraform.tfvars from .env, so the five Discord values are typed
 * once instead of twice. Run: npm run tfvars
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline/promises";
import { config } from "../src/config.js";

const OUT = "infra/terraform.tfvars";

const required = {
  discord_app_id: config.DISCORD_APP_ID,
  discord_public_key: config.DISCORD_PUBLIC_KEY,
  discord_bot_token: config.DISCORD_BOT_TOKEN,
  discord_channel_id: config.DISCORD_CHANNEL_ID,
  owner_user_id: config.OWNER_USER_ID,
};

const missing = Object.entries(required).filter(([, v]) => !v).map(([k]) => k.toUpperCase());
if (missing.length) {
  console.error(`These are still empty in .env:\n${missing.map((m) => `  - ${m}`).join("\n")}`);
  console.error("\nFill them in, then run this again.");
  process.exit(1);
}

if (existsSync(OUT)) {
  const existing = readFileSync(OUT, "utf8");
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const answer = (await rl.question(`${OUT} already exists. Overwrite? [y/N] `)).trim().toLowerCase();
  rl.close();
  if (answer !== "y") {
    console.log("Left it alone.");
    process.exit(0);
  }
  if (!existing.includes("discord_app_id")) {
    console.warn("Note: the old file did not look like Discord tfvars. Overwriting anyway.");
  }
}

const lines = [
  "# Generated by `npm run tfvars` from .env. Gitignored: it holds the bot token.",
  "",
  ...Object.entries(required).map(([k, v]) => `${k.padEnd(19)}= ${JSON.stringify(v)}`),
  "",
  `aws_region         = ${JSON.stringify(config.AWS_REGION)}`,
  `tz_name            = ${JSON.stringify(config.TZ_NAME)}`,
  `start_date         = ${JSON.stringify(config.START_DATE)}`,
  "",
];

writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`wrote ${OUT}`);
console.log("\nNext:\n  npm run build:lambda\n  terraform -chdir=infra apply");
